FROM python:3.10-slim

WORKDIR /app

RUN mkdir static && mkdir templates && mkdir PDFs && mkdir Script

COPY requirements.txt .

COPY Script/ ./Script/

COPY PDFs/ ./PDFs/

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

CMD ["python","Script/grobit.py"]


