FROM python:3.10-slim

WORKDIR /app

RUN mkdir static && mkdir templates

COPY main.py .

COPY static/ ./static/

COPY templates/ ./templates/

RUN pip install --upgrade pip

RUN pip install flask

CMD ["python","main.py"]


