name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-latest]
          python-version: [3.9]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker images
        run: docker-compose build

      - name: Start services and copy outputs from assessment_container
        working-directory: ./Individual_Assessment_1
        run: |
          mkdir -p static 
          mkdir -p templates
          docker-compose up -d
          docker cp assessment_container:/app/static ./static
          docker cp assessment_container:/app/templates ./templates  

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pytest
        run: |
          pip install pytest
          
      - name: Install dependencies
        working-directory: ./Individual_Assessment_1
        run: |
          pip install --no-cache-dir -r requirements.txt
      - name: Run tests
        run: |
          pytest
      - name: Tear down containers
        run: docker-compose down